#!/bin/bash

cd ~/emacs/emacs.d
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/emacs/emacs.d/ke-doom
git clone --depth 1 https://github.com/hlissner/doom-emacs
~/emacs/emacs.d/vanilla-doom 
